# Generated by Django 4.0.5 on 2022-06-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='data',
            name='country',
        ),
        migrations.AlterField(
            model_name='data',
            name='category',
            field=models.CharField(choices=[(1, 'Non-Alloy Finished Steel')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='state',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='type',
            field=models.CharField(choices=[(0, 'Bars and Rods'), (1, 'Stainless Steel'), (2, 'HR Coil'), (3, 'Galvanized Iron Coil')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
