# Generated by Django 4.0.5 on 2022-06-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_data_options_remove_data_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='category',
            field=models.PositiveIntegerField(choices=[(1, 'Non-Alloy Finished Steel')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Bars and Rods'), (1, 'Stainless Steel'), (2, 'HR Coil'), (3, 'Galvanized Iron Coil')], null=True),
        ),
    ]
