# Generated by Django 4.0.5 on 2022-06-07 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_data_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='year',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(2018), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
