# Generated by Django 4.0.5 on 2022-06-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_data_consumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='consumption',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
