# Generated by Django 4.0.5 on 2022-06-08 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_data_consumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='year',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(2017), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
