# Generated by Django 4.0.5 on 2022-06-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_data_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'Jammu and Kashmir'), (2, 'Andhra Pradesh'), (3, 'Arunachal Pradesh'), (4, 'Assam'), (5, 'Bihar'), (6, 'Chhattisgarh'), (7, 'Goa'), (8, 'Gujarat'), (9, 'Haryana'), (10, 'Himachal Pradesh'), (11, 'Jharkhand'), (12, 'Karnataka'), (13, 'Kerala'), (14, 'Madhya Pradesh'), (15, 'Maharashtra'), (16, 'Manipur'), (17, 'Meghalaya'), (18, 'Mizoram'), (19, 'Nagaland'), (20, 'Odisha'), (21, 'Punjab'), (22, 'Rajasthan'), (23, 'Sikkim'), (24, 'Tamil Nadu'), (25, 'Telangana'), (26, 'Tripura'), (27, 'Uttar Pradesh'), (28, 'Uttarakhand'), (29, 'West Bengal'), (30, 'Chandigarh'), (31, 'Delhi')], null=True),
        ),
    ]
